version: '3.7'

services:
  server:
    build: server
    container_name: CUPhotoContest_Server
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
  
  proxy:
    image: nginx:latest
    container_name: CUPhotoContest_Proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    restart: always
    
    
